server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: local_logs
    pipeline_stages:
      - regex:
          # 解析日志的各个部分
          expression: '^\[(?P<timestamp>[^\]]*)\] \[(?P<service>[^\]]*)\] \[(?P<level>[^\]]*)\] (?P<message>.*)'
      
      - labels:
          level:  # 提取日志级别作为标签
          service:  # 提取服务名作为标签
      
      - timestamp:
          source: timestamp
          format: "2006-01-02 15:04:05.000"  # Go 语言时间格式
      
      - output:
          # 指定 source 为 message
          source: message
          format: json

    static_configs:
      - targets: [localhost]
        labels:
          job: local_logs
          __path__: /var/log/*.log
