on: [push]

jobs:
  Notion_Hook_job:
    runs-on: ubuntu-latest
    name: A job to connect to Notion
    steps:
      - name: Connect to Notion step
        id: notion
        uses: alessandrobelli/NotionHook@1.0
        with:
          notion_secret: ${{ secrets.NOTION_SECRET }}
          notion_database: ${{ secrets.NOTION_DATABASE }}
          Title: ${{ github.event.head_commit.message }}
          Description: ${{ github.event.head_commit.message }}
          Url: ${{ github.event.head_commit.url }}
          Project: "NexusTrader"
          Id: ${{ github.sha }}
          files_format: "text-list"
